# -*- coding: utf-8 -*-
"""Generator Mock/Synthetic Data Penjualan & Stok.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1euwuYD0enXAgYaK48LQkE0EiqOdad53_
"""

import pandas as pd
import numpy as np
from datetime import datetime, timedelta

# Set seed agar hasil generate konsisten (Memenuhi standar NFR-02 SRS)
np.random.seed(42)

# 1. Generate Mock Data Poktan
poktan_data = {
    'id_poktan': [1, 2, 3, 4, 5],
    'nama_poktan': ['Suka Maju', 'Tani Makmur', 'Sumber Rejeki', 'Karya Bhakti', 'Mekar Sari'],
    'wilayah_dusun': ['Dusun Utara', 'Dusun Selatan', 'Dusun Timur', 'Dusun Barat', 'Dusun Tengah']
}
df_poktan = pd.DataFrame(poktan_data)

# 2. Generate Mock Data Komoditas
komoditas_data = {
    'id_komoditas': [1, 2, 3],
    'nama_komoditas': ['Pupuk Organik Cair', 'Pupuk NPK Padat', 'Benih Padi Ciherang'],
    'satuan': ['Liter', 'Kg', 'Kg'],
    'harga_satuan_estimasi': [25000, 15000, 85000]
}
df_komoditas = pd.DataFrame(komoditas_data)

# 3. Generate Mock Data Permintaan Poktan (Agregasi Mingguan sesuai FR-01)
start_date = datetime(2025, 1, 1)
end_date = datetime(2026, 8, 31)

permintaan_list = []
current_date = start_date
id_permintaan = 1

while current_date <= end_date:
    for p_id in df_poktan['id_poktan']:
        for k_id in df_komoditas['id_komoditas']:
            # Simulasi volume: Benih butuh lebih sedikit dibanding Pupuk
            if k_id == 3:
                base_demand = np.random.normal(50, 10)
            else:
                base_demand = np.random.normal(300, 80)

            # Hindari nilai negatif dan bulatkan
            volume = max(10, round(base_demand, 2))

            permintaan_list.append({
                'id_permintaan': id_permintaan,
                'id_poktan': p_id,
                'id_komoditas': k_id,
                'tanggal_permintaan': current_date.strftime('%Y-%m-%d'),
                'volume_permintaan': volume,
                'status_data': 'Mentah'
            })
            id_permintaan += 1

    # Loncat 7 hari untuk agregasi mingguan
    current_date += timedelta(days=7)

df_permintaan = pd.DataFrame(permintaan_list)

# 4. Generate Mock Data Stok Gudang (Snapshot stok saat ini)
stok_list = []
id_stok = 1

for k_id in df_komoditas['id_komoditas']:
    # Asumsi stok aktual di gudang
    volume_stok = np.random.randint(500, 2500)
    # Threshold warning (FR-06): Benih diset lebih rendah
    threshold = 200 if k_id == 3 else 1000

    stok_list.append({
        'id_stok': id_stok,
        'id_komoditas': k_id,
        'tanggal_catat': datetime(2026, 9, 1).strftime('%Y-%m-%d'), # Stok bulan berjalan
        'volume_stok_aktual': volume_stok,
        'threshold_minimum': threshold
    })
    id_stok += 1

df_stok = pd.DataFrame(stok_list)

# 5. Export semua data ke dalam format CSV
df_poktan.to_csv('mock_poktan.csv', index=False)
df_komoditas.to_csv('mock_komoditas.csv', index=False)
df_permintaan.to_csv('mock_permintaan.csv', index=False)
df_stok.to_csv('mock_stok.csv', index=False)

print("✅ Data sintetik berhasil di-generate!")
print(f"Total record permintaan mingguan yang siap di-ETL: {len(df_permintaan)} baris.")